### ISSUE TITLE
Make the pretrained model available

### ISSUE THREAD

**Issue by Linlinzhao** [DSPsleeporg/smiles-transformer#10]
Hi, I would like to try out your pretrained models, it has been a while after sending a request for downloading the models. Why don't you simply make them accessible to everyone? Or you would like to know who is using the models?

**Comment by shionhonda** [comment]
Thanks for pointing out. It was accessible to everyone at Google Drive, but I just realized that my university's Google account was inactivated because I graduated last March. I'm reaching out to my former laboratory to get it re-uploaded somewhere else, so could you please wait for several more days?

**Comment by shionhonda** [comment]
I updated README. Does this link work?
https://drive.google.com/file/d/1LwE2BzvtDaPGYv0OR6iBjmsqoloH885N/view?usp=sharing

**Comment by linlinzhao** [comment]
Thanks a lot, the link worked. I have downloaded it.
